### ISSUE TITLE
Frontend: Favorite/Star Button Company Card Component

### ISSUE THREAD

**Issue by modopo** [team-JWMT/food-finder-explorer-frontend#12]
- [ ] Based on login status and what page the user is at, render "add to collection/favorite page" button to the Company Card component
- [ ] Make a variable that's an empty array to store a list of favorited companies
- [ ] When add button is clicked, store selected Company Object into the state
- [ ] When more Company are added, keep adding to the state

**Comment by Zjet95** [comment]
@modopo I have a question in regards to how to go about starting task #1 when we meet tomorrow. Maybe you can help spart some ideas, I know we will use conditional rendering for that piece but am not sure exactly how to implement.
